### ISSUE TITLE
DarkSky.net no longer accepting new signups

### ISSUE THREAD

**Issue by TheEndIsNear** [drizzle-org/drizzle#2]
Now that DarkSky.net has been bought by Apple they are no longer allowing new signups for using the darksky API and have announced they  will be ending support at the end of 2021, a new weather API will need to be brought in to support local weather

**Comment by mcrumm** [comment]
OpenWeatherMap is free up to 1000 calls a day, and has a [migration guide](https://openweathermap.org/darksky-openweather) from DarkSky

**Comment by supersimple** [comment]
My current PR is centered around the climacell API (which i preferred because of the availability for predicted rainfall.) My goal is to make the forecaster accept a protocol so that a user can choose their API.
